version: '3'

services:
  php-fpm:
    image: php:7.2-fpm
    build:
      context: ./php/7.2
      dockerfile: dockerfile
    volumes:
      - ${WWWROOT}:/var/www/html
    networks:
      - backend
    depends_on:
      - mariadb
      - redis
  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: dockerfile
    volumes:
      - ${WWWROOT}:/var/www/html
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    depends_on:
      - php-fpm
  mariadb:
    image: mariadb
    build:
      context: ./mariadb
      dockerfile: dockerfile
    volumes:
      - ./mariadb/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - frontend
      - backend
  redis:
    image: redis
    build:
      context: ./redis
      dockerfile: dockerfile
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.101.0/24"

  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.102.0/24"

volumes:
  mariadb:
    driver: local
  redis:
    driver: local
